### PR TITLE
Ensure unique element IDs

### LINKED ISSUE #6: Non-unique element IDs when using several VAnnotators on same page
Calculation of the BaseEntities' `margin` props relies on the bounding rect of an element with hard-coded ID `container` (see [here](https://github.com/doccano/v-annotator/blob/fd31fbb8ff9d42340df48dcd2adeb196083005d2/src/components/VAnnotator.vue#L268)). When there are multiple VAnnotator components on the same page, there will be several elements with ID `container`, and the position of the entities will be incorrectly calculated.

Looking through the code, I also noticed other places with similar problems [here](https://github.com/doccano/v-annotator/blob/fd31fbb8ff9d42340df48dcd2adeb196083005d2/src/components/VAnnotator.vue#L150-L152) and [here](https://github.com/doccano/v-annotator/blob/fd31fbb8ff9d42340df48dcd2adeb196083005d2/src/components/VLine.vue#L218-L223).

My idea for fixing this would be to generate a random ID for each VAnnotator component and append it to the IDs of the elements (e.g. `container-7490b8b5-d8f3-4106-8377-fce9f9fb6879`, `text-7490b8b5-d8f3-4106-8377-fce9f9fb6879` etc.). @Hironsan: if you agree with this approach, I'm happy to open a PR.

Or would you prefer a solution using [template refs](https://vuejs.org/guide/essentials/template-refs.html)?

### PR DESCRIPTION
**Pull request by saeub**
Ensure that `id` attribute values on HTML elements are unique. This allows several `VAnnotator` components to be placed on the same page.

I added a second `VAnnotator` component to `App.vue` for testing.

Closes #6.

### CODE REVIEW

**Comment by saeub** [comment]
I found some more duplicate IDs in the SVG, and I think it might be related to doccano/doccano#1863. I'm going to investigate this further, please don't merge yet.

**Comment by Hironsan** [comment]
OK. I'm looking forward to it.

**Comment by saeub** [comment]
As a nice side-effect, f8c7391 also seems to enable annotating spans across lines on Firefox (doccano/doccano#1863). However, there is still a problem when adding another overlapping span across the same line break:

image

This works in Chromium, but not in Firefox. The problem is that `window.getSelection()` returns strange `anchorNode`s when there are other nodes between the two `<text>` nodes (in this, case the `<g>` node from `BaseEntity`). I couldn't get this to work, and it's not related to the issue I'm trying to fix in this PR, so I'm leaving it at that.

**Comment by Hironsan** [comment]
Thanks!

**Pull request merged**
